### ISSUE TITLE
About Imagenet-10/dogs Tiny-Imagenet over clustering

### ISSUE THREAD

**Issue by mynameischaos** [Raymond-sci/PICA#1]
Hi~  Please help me.
I want to know do you use over clustering in Imagenet-10/dogs dataset?  and how much data are you using? 
Thank you very much.

**Comment by Raymond-sci** [comment]
yes, as described in our paper, we set the size of over-clustering to 70 on all the benchmarks except for the tiny imagenet (700).

**Comment by Raymond-sci** [comment]
Close due to inactivation. Please feel free to re-open if needed.
