### ISSUE TITLE
The result for Imagenet-10 is far away from that reported in the article.

### ISSUE THREAD

**Issue by ChongC1990** [Raymond-sci/PICA#2]
Hi, Jiabo

I try to recover the results shown in the article by this code. The results for CIFAR-10 and CIFAR-100 are reasonable, but a big gap for Imagenet-10. Can you tell me the hyper-parameters you use for this dataset? Thank you so much.

**Comment by Raymond-sci** [comment]
there is no much difference between training on different benchmarks except for the input size. For ImageNet10, we resized the training inputs to 112x112 and random cropped them to 96x96. Please refer to table 1 in "Deep Comprehensive Correlation Mining for Image Clustering" for more details. Besides, please also be sure that you are using the same selected categories as described in https://github.com/vector-1127/DAC/tree/master/Datasets_description. 

If still fail to reproduce the results, can you please provide me with all the config files you used so that I get the chance to address the problem.

**Comment by ChongC1990** [comment]
I did five tests according to your advice.  The best MAP for ImageNet-10 is only 0.83, did not reach the average level reported in the article.  Here are the config files
`#############
# base cfgs #
#############

## args for training
log_file: True
log_tfb: True
display_freq: 50

## args for network
network: resnet34
net_sobel: True

## args for transforms
data_nrepeat: 3
#tfm_scale: (0.2, 1.)
#tfm_ratio: (3./4., 4./3.)
tfm_colorjitter: (0.4, 0.4, 0.4, 0.4)
tfm_random_grayscale: 0.2
tfm_random_hflip: 0.5

## args for lr policy
base_lr: 1e-4
lr_policy: fixed
## args for optimizer
optimizer: adam
optim_weight_decay: 0.

## args for loader
num_workers: 8
batch_size: 256

## args for session
session_root: "baseline_sessions"`
`##################
# cfgs for ImageNet10 #
##################

## args for network
net_avgpool_size: 7
net_heads:
  - 70
  - 10

## args for dataset and dataloader
dataset: imagenet10
data_root: /gruntdata5/Dataset/test
tfm_means: (0.485, 0.456, 0.406)
tfm_stds: (0.229, 0.224, 0.225)
tfm_size: (96, 96)
tfm_resize: 112

## smaller batch size for lower memory consumption
batch_size: 128
`

Is there any difference from the configuration you use？

**Comment by Raymond-sci** [comment]
If I didn't miss anything, we did augment the training inputs by random cropping, so please uncomment `tfm_scale` and `tfm_ratio`. Besides, the batch size was set to 64. Although I assume the setting of batch size should not make much difference to the outcomes, I'll like to mention it as another difference I found from the provided configurations.

**Comment by ZhiyuanDang** [comment]
> If I didn't miss anything, we did augment the training inputs by random cropping, so please uncomment `tfm_scale` and `tfm_ratio`. Besides, the batch size was set to 64. Although I assume the setting of batch size should not make much difference to the outcomes, I'll like to mention it as another difference I found from the provided configurations.

Hi, how to construct ImageNet-10, ImageNet-Dogs, and Tiny-ImageNet datasets for your code? Could you please provide some related code or links? Thanks!

**Comment by Raymond-sci** [comment]
@ZhiyuanDang 

Please refer to https://tiny-imagenet.herokuapp.com/ for the introduction of Tiny-ImageNet and see https://github.com/vector-1127/DAC/tree/master/Datasets_description for ImageNet-10/Dogs.

P.S. the data loading issue is less related to the topic of this thread, could you please open a new issue if you have further questions?

**Comment by Raymond-sci** [comment]
Closed due to inactivity. Feel free to re-open if needed.

**Comment by Raymond-sci** [comment]
Closed due to inactivity. Feel free to re-open if needed.
