### ISSUE TITLE
Running on multi-GPUs

### ISSUE THREAD

**Issue by nairouz** [Raymond-sci/PICA#3]
Hello,

I am trying to run your code on STL10. Although I have followed the provided instructions, my results (ACC, NMI, ARI) remain nearly constant during the training process. 

I use the following command to run the program:
`python main.py --cfgs configs/base.yaml configs/stl10.yaml --data-root /home/mrabah_n/code/Pytorch/data/STL-10/ --gpus 1,2`

Here you may find my log.txt file:
[https://pastebin.com/n132spT9](https://pastebin.com/n132spT9)

Here are  [my configurations](https://pastebin.com/csUWNR2m):

```
base_lr: 0.0001
batch_size: 128
brief: false
cfgs:
- configs/base.yaml
- configs/stl10.yaml
data_nrepeat: 3
data_root: /home/mrabah_n/code/Pytorch/data/STL-10/
dataset: stl10
debug: false
display_freq: 50
gpus: 1,2
log_file: true
log_tfb: true
lr_policy: fixed
max_epochs: 200
net_avgpool_size: 7
net_cin: 3
net_cout: 1000
net_freeze: []
net_heads:
- 70
- 10
net_sobel: true
network: resnet34
num_workers: 8
optim_amsgrad: false
optim_beta:
- 0.9
- 0.999
optim_eps: 1.0e-08
optim_weight_decay: 0.0
optimizer: adam
pica_lamda: 2.0
restart: false
resume: null
seed: null
session: 20200629-012039
session_root: sessions
tfm_colorjitter:
- 0.4
- 0.4
- 0.4
- 0.4
tfm_means:
- 0.485
- 0.456
- 0.406
tfm_random_grayscale: 0.2
tfm_random_hflip: 0.5
tfm_ratio:
- 0.75
- 1.3333333333333333
tfm_resize: 112
tfm_scale:
- 0.2
- 1.0
tfm_size:
- 96
- 96
tfm_stds:
- 0.229
- 0.224
- 0.225
transform: default
```
Thanks,

**Comment by Raymond-sci** [comment]
seems like there is a problem when training with multiple GPUs. (we used one device at a time in our own experiments).  We have temporarily disabled this function, you may want to run the current version with a single GPU.

**Comment by nairouz** [comment]
Thanks, Jiabo. I confirm that the problem is related to multi-GPUs execution of the code. I tried on CIFAR10 with a single GPU, the computed metrics are progressing during the training process.

**Comment by Raymond-sci** [comment]
No problem. Issue closed. will manage time for this problem.
