### ISSUE TITLE
Data loading Issues

### ISSUE THREAD

**Issue by ZhiyuanDang** [Raymond-sci/PICA#4]
I hope the author provides the related loading code or some instructions for loading other datasets such as ImageNet-10, ImageNet-Dogs, and Tiny-ImageNet. Thanks!

**Comment by Raymond-sci** [comment]
Please see below a brief instruction on constructing ImageNet-related datasets:

## Tiny-ImageNet

1. Download data from https://tiny-imagenet.herokuapp.com/
2. Organise data according to and load them by [`torchvision.datasets.ImageFolder` ](https://pytorch.org/docs/stable/torchvision/datasets.html#imagefolder)
## ImageNet Subsets (ImageNet-10/Dogs)

1. Download data from http://www.image-net.org/
2. Load data by [`torchvision.datasets.ImageNet`](https://pytorch.org/docs/stable/torchvision/datasets.html#imagenet)
3. Implement the category-wise subset interface referring to the instance-wise one [`torch.utils.data.Subset`](https://pytorch.org/docs/stable/data.html)
4. Get the selected categories for both datasets (ImageNet-10/Dogs) from https://github.com/vector-1127/DAC/tree/master/Datasets_description

**Comment by ZhiyuanDang** [comment]
Hi, thanks for your reply. I successfully run the code over Tiny-ImageNet dataset. However, the total ImageNet dataset is too large to download and process. Besides that, I still am waiting for Access Permission of ImageNet. So, would you mind if I request you to upload the zip or rar file of the ImageNet-10 and ImageNet-dogs?

**Comment by Raymond-sci** [comment]
I afraid that I don't get the right to distribute the dataset, that's also why you need to get their permission to use the data.

**Comment by ZhiyuanDang** [comment]
Fine. I will find another way to get the dataset. Thanks for your help!
