### ISSUE TITLE
CIFAR10 xml

### ISSUE THREAD

**Issue by miziha-zp** [Raymond-sci/PICA#6]
it seems like the cifar10.xml is not uploaded, and in your code, I don't it is compatible to cifar10.
in your paper `Effect of over-clustering` show the "over-clustering" setting for CIFAR10, is it means set xml likes below:
```xml
net_heads
  - 70
  - 10
```

**Comment by Raymond-sci** [comment]
If I didn't miss anything, it should be set in this way.

**Comment by miziha-zp** [comment]
thx for your reply.close this issue for solved.
